module.exports = [
  {
    'bjTotal': null,
    'zlzgNum': null,
    'dxtxNum': null,
    'aiTodayBjNum': null,
    'aiJkTotal': null,
    'longitude': '113.106745150',
    'latitude': '23.028282218',
    'area': '禅城区',
    'deviceName': '东方广场3号球机',
    'deviceBjTotal': 454,
    'proportion': '4.91%',
    'list': null,
    'title': null,
    'warnTypeCode': null,
    'deviceChanel': 'UN68QrpHA1BJDDJGTDK9DK'
  },
  {
    'bjTotal': null,
    'zlzgNum': null,
    'dxtxNum': null,
    'aiTodayBjNum': null,
    'aiJkTotal': null,
    'longitude': '113.112198695',
    'latitude': '23.021173033',
    'area': '禅城区',
    'deviceName': '妇幼保健院3号球机',
    'deviceBjTotal': 444,
    'proportion': '4.81%',
    'list': null,
    'title': null,
    'warnTypeCode': null,
    'deviceChanel': 'UN68QrpHA1BI9ESJ93VA4V'
  },
  {
    'bjTotal': null,
    'zlzgNum': null,
    'dxtxNum': null,
    'aiTodayBjNum': null,
    'aiJkTotal': null,
    'longitude': '113.124940413',
    'latitude': '23.038490896',
    'area': '禅城区',
    'deviceName': '百花广场3号球机',
    'deviceBjTotal': 307,
    'proportion': '3.32%',
    'list': null,
    'title': null,
    'warnTypeCode': null,
    'deviceChanel': 'UN68QrpHA1C8R84P1LFPSN'
  },
  {
    'bjTotal': null,
    'zlzgNum': null,
    'dxtxNum': null,
    'aiTodayBjNum': null,
    'aiJkTotal': null,
    'longitude': '113.106730729',
    'latitude': '23.028834917',
    'area': '禅城区',
    'deviceName': '中山公园4号球机',
    'deviceBjTotal': 262,
    'proportion': '2.84%',
    'list': null,
    'title': null,
    'warnTypeCode': null,
    'deviceChanel': 'UN68QrpHA1BI9ESJ98O2TV'
  },
  {
    'bjTotal': null,
    'zlzgNum': null,
    'dxtxNum': null,
    'aiTodayBjNum': null,
    'aiJkTotal': null,
    'longitude': '113.100420158',
    'latitude': '23.034302985',
    'area': '禅城区',
    'deviceName': '妇幼保健院1号球机',
    'deviceBjTotal': 254,
    'proportion': '2.75%',
    'list': null,
    'title': null,
    'warnTypeCode': null,
    'deviceChanel': 'UN68QrpHA1BI9ESJ94TR2L'
  },
  {
    'bjTotal': null,
    'zlzgNum': null,
    'dxtxNum': null,
    'aiTodayBjNum': null,
    'aiJkTotal': null,
    'longitude': '113.113186052',
    'latitude': '23.026888638',
    'area': '禅城区',
    'deviceName': '东方广场6号球机',
    'deviceBjTotal': 250,
    'proportion': '2.71%',
    'list': null,
    'title': null,
    'warnTypeCode': null,
    'deviceChanel': 'UN68QrpHA1C8R84P1Q8F5Q'
  },
  {
    'bjTotal': null,
    'zlzgNum': null,
    'dxtxNum': null,
    'aiTodayBjNum': null,
    'aiJkTotal': null,
    'longitude': '113.116878669',
    'latitude': '23.040133395',
    'area': '禅城区',
    'deviceName': '佛平路-平桂街1号球机',
    'deviceBjTotal': 248,
    'proportion': '2.68%',
    'list': null,
    'title': null,
    'warnTypeCode': null,
    'deviceChanel': 'UN68QrpHA1C8R84P1Q8EGU'
  },
  {
    'bjTotal': null,
    'zlzgNum': null,
    'dxtxNum': null,
    'aiTodayBjNum': null,
    'aiJkTotal': null,
    'longitude': '113.116964532',
    'latitude': '23.040699363',
    'area': '禅城区',
    'deviceName': '火车站1号球机',
    'deviceBjTotal': 227,
    'proportion': '2.46%',
    'list': null,
    'title': null,
    'warnTypeCode': null,
    'deviceChanel': 'UN68QrpHA1C8R84P1Q8EK2'
  },
  {
    'bjTotal': null,
    'zlzgNum': null,
    'dxtxNum': null,
    'aiTodayBjNum': null,
    'aiJkTotal': null,
    'longitude': '113.116635296',
    'latitude': '23.039369992',
    'area': '禅城区',
    'deviceName': '中医院2号球机',
    'deviceBjTotal': 217,
    'proportion': '2.35%',
    'list': null,
    'title': null,
    'warnTypeCode': null,
    'deviceChanel': 'UN68QrpHA1C8R84P1Q8EN1'
  },
  {
    'bjTotal': null,
    'zlzgNum': null,
    'dxtxNum': null,
    'aiTodayBjNum': null,
    'aiJkTotal': null,
    'longitude': '113.106329093',
    'latitude': '23.042543063',
    'area': '禅城区',
    'deviceName': '同济市场4号球机',
    'deviceBjTotal': 207,
    'proportion': '2.24%',
    'list': null,
    'title': null,
    'warnTypeCode': null,
    'deviceChanel': 'UN68QrpHA1C8R84P1KH8I9'
  },
  {
    'bjTotal': null,
    'zlzgNum': null,
    'dxtxNum': null,
    'aiTodayBjNum': null,
    'aiJkTotal': null,
    'longitude': '113.112141476',
    'latitude': '23.021673083',
    'area': '禅城区',
    'deviceName': '南堤市场2号球机',
    'deviceBjTotal': 203,
    'proportion': '2.20%',
    'list': null,
    'title': null,
    'warnTypeCode': null,
    'deviceChanel': 'UN68QrpHA1BI9ESJ96QVB5'
  },
  {
    'bjTotal': null,
    'zlzgNum': null,
    'dxtxNum': null,
    'aiTodayBjNum': null,
    'aiJkTotal': null,
    'longitude': '113.098574636',
    'latitude': '23.034328790',
    'area': '禅城区',
    'deviceName': '百花广场4号球机',
    'deviceBjTotal': 203,
    'proportion': '2.20%',
    'list': null,
    'title': null,
    'warnTypeCode': null,
    'deviceChanel': 'UN68QrpHA1BI9ESJ95SCVQ'
  },
  {
    'bjTotal': null,
    'zlzgNum': null,
    'dxtxNum': null,
    'aiTodayBjNum': null,
    'aiJkTotal': null,
    'longitude': '113.103453135',
    'latitude': '23.037801223',
    'area': '禅城区',
    'deviceName': '百花广场5号球机',
    'deviceBjTotal': 201,
    'proportion': '2.18%',
    'list': null,
    'title': null,
    'warnTypeCode': null,
    'deviceChanel': 'UN68QrpHA1C8R84P1P9TPM'
  },
  {
    'bjTotal': null,
    'zlzgNum': null,
    'dxtxNum': null,
    'aiTodayBjNum': null,
    'aiJkTotal': null,
    'longitude': '113.112225708',
    'latitude': '23.044964964',
    'area': '禅城区',
    'deviceName': '东方广场5号球机',
    'deviceBjTotal': 192,
    'proportion': '2.08%',
    'list': null,
    'title': null,
    'warnTypeCode': null,
    'deviceChanel': 'UN68QrpHA1C8R84P1P9T2B'
  },
  {
    'bjTotal': null,
    'zlzgNum': null,
    'dxtxNum': null,
    'aiTodayBjNum': null,
    'aiJkTotal': null,
    'longitude': '113.113871987',
    'latitude': '23.044913736',
    'area': '禅城区',
    'deviceName': '东方广场4号球机',
    'deviceBjTotal': 186,
    'proportion': '2.01%',
    'list': null,
    'title': null,
    'warnTypeCode': null,
    'deviceChanel': 'UN68QrpHA1C8R84P1P9T4P'
  },
  {
    'bjTotal': null,
    'zlzgNum': null,
    'dxtxNum': null,
    'aiTodayBjNum': null,
    'aiJkTotal': null,
    'longitude': '113.103840301',
    'latitude': '23.026767288',
    'area': '禅城区',
    'deviceName': '同济市场3号球机',
    'deviceBjTotal': 182,
    'proportion': '1.97%',
    'list': null,
    'title': null,
    'warnTypeCode': null,
    'deviceChanel': 'UN68QrpHA1C8R84P1R70ID'
  },
  {
    'bjTotal': null,
    'zlzgNum': null,
    'dxtxNum': null,
    'aiTodayBjNum': null,
    'aiJkTotal': null,
    'longitude': '113.111554558',
    'latitude': '23.021725228',
    'area': '禅城区',
    'deviceName': '人民路交叉口1号球机_1',
    'deviceBjTotal': 174,
    'proportion': '1.88%',
    'list': null,
    'title': null,
    'warnTypeCode': null,
    'deviceChanel': 'UN68QrpHA1BI9ESJ96QV3Q'
  },
  {
    'bjTotal': null,
    'zlzgNum': null,
    'dxtxNum': null,
    'aiTodayBjNum': null,
    'aiJkTotal': null,
    'longitude': '113.106372026',
    'latitude': '23.042529963',
    'area': '禅城区',
    'deviceName': '火车站3号球机',
    'deviceBjTotal': 157,
    'proportion': '1.70%',
    'list': null,
    'title': null,
    'warnTypeCode': null,
    'deviceChanel': 'UN68QrpHA1BK3KTR3SDVB0'
  },
  {
    'bjTotal': null,
    'zlzgNum': null,
    'dxtxNum': null,
    'aiTodayBjNum': null,
    'aiJkTotal': null,
    'longitude': '113.099432996',
    'latitude': '23.034355377',
    'area': '禅城区',
    'deviceName': '百花广场2号球机',
    'deviceBjTotal': 156,
    'proportion': '1.69%',
    'list': null,
    'title': null,
    'warnTypeCode': null,
    'deviceChanel': 'UN68QrpHA1BI9ESJ94TS0T'
  },
  {
    'bjTotal': null,
    'zlzgNum': null,
    'dxtxNum': null,
    'aiTodayBjNum': null,
    'aiJkTotal': null,
    'longitude': '113.112999124',
    'latitude': '23.039695662',
    'area': '禅城区',
    'deviceName': '华强广场3号球机',
    'deviceBjTotal': 155,
    'proportion': '1.68%',
    'list': null,
    'title': null,
    'warnTypeCode': null,
    'deviceChanel': 'UN68QrpHA1C8R84P1Q8EOV'
  },
  {
    'bjTotal': null,
    'zlzgNum': null,
    'dxtxNum': null,
    'aiTodayBjNum': null,
    'aiJkTotal': null,
    'longitude': '113.115790308',
    'latitude': '23.044954966',
    'area': '禅城区',
    'deviceName': '华强广场2号球机',
    'deviceBjTotal': 155,
    'proportion': '1.68%',
    'list': null,
    'title': null,
    'warnTypeCode': null,
    'deviceChanel': 'UN68QrpHA1C8R84P1KH8V0'
  },
  {
    'bjTotal': null,
    'zlzgNum': null,
    'dxtxNum': null,
    'aiTodayBjNum': null,
    'aiJkTotal': null,
    'longitude': '113.111873084655',
    'latitude': '23.021143130198',
    'area': '禅城区',
    'deviceName': '同济市场4号球机',
    'deviceBjTotal': 154,
    'proportion': '1.67%',
    'list': null,
    'title': null,
    'warnTypeCode': null,
    'deviceChanel': 'UN68QrpHA1C8R84P1KH8I9'
  },
  {
    'bjTotal': null,
    'zlzgNum': null,
    'dxtxNum': null,
    'aiTodayBjNum': null,
    'aiJkTotal': null,
    'longitude': '113.116276886',
    'latitude': '23.047139624',
    'area': '禅城区',
    'deviceName': '华强广场1号球机',
    'deviceBjTotal': 150,
    'proportion': '1.62%',
    'list': null,
    'title': null,
    'warnTypeCode': null,
    'deviceChanel': 'UN68QrpHA1C8R84P1KH933'
  },
  {
    'bjTotal': null,
    'zlzgNum': null,
    'dxtxNum': null,
    'aiTodayBjNum': null,
    'aiJkTotal': null,
    'longitude': '113.116793062',
    'latitude': '23.035251451',
    'area': '禅城区',
    'deviceName': '同济市场5号球机',
    'deviceBjTotal': 147,
    'proportion': '1.59%',
    'list': null,
    'title': null,
    'warnTypeCode': null,
    'deviceChanel': 'UN68QrpHA1C8R84P1KH8QV'
  },
  {
    'bjTotal': null,
    'zlzgNum': null,
    'dxtxNum': null,
    'aiTodayBjNum': null,
    'aiJkTotal': null,
    'longitude': '113.104898675',
    'latitude': '23.034058228',
    'area': '禅城区',
    'deviceName': '百花广场1号球机',
    'deviceBjTotal': 141,
    'proportion': '1.53%',
    'list': null,
    'title': null,
    'warnTypeCode': null,
    'deviceChanel': 'UN68QrpHA1C8R84P1KH8SQ'
  },
  {
    'bjTotal': null,
    'zlzgNum': null,
    'dxtxNum': null,
    'aiTodayBjNum': null,
    'aiJkTotal': null,
    'longitude': '113.104440155',
    'latitude': '23.043015748',
    'area': '禅城区',
    'deviceName': '火车站2号球机',
    'deviceBjTotal': 138,
    'proportion': '1.49%',
    'list': null,
    'title': null,
    'warnTypeCode': null,
    'deviceChanel': 'UN68QrpHA1C8R84P1MEATC'
  },
  {
    'bjTotal': null,
    'zlzgNum': null,
    'dxtxNum': null,
    'aiTodayBjNum': null,
    'aiJkTotal': null,
    'longitude': '113.106343477',
    'latitude': '23.042516821',
    'area': '禅城区',
    'deviceName': '南堤市场3号球机',
    'deviceBjTotal': 126,
    'proportion': '1.36%',
    'list': null,
    'title': null,
    'warnTypeCode': null,
    'deviceChanel': 'UN68QrpHA1C8HR7N69BT7B'
  },
  {
    'bjTotal': null,
    'zlzgNum': null,
    'dxtxNum': null,
    'aiTodayBjNum': null,
    'aiJkTotal': null,
    'longitude': '113.117050383',
    'latitude': '23.041462607',
    'area': '禅城区',
    'deviceName': '市二医院3号球机',
    'deviceBjTotal': 125,
    'proportion': '1.35%',
    'list': null,
    'title': null,
    'warnTypeCode': null,
    'deviceChanel': 'UN68QrpHA1C8R84P1P9TRB'
  },
  {
    'bjTotal': null,
    'zlzgNum': null,
    'dxtxNum': null,
    'aiTodayBjNum': null,
    'aiJkTotal': null,
    'longitude': '113.105757625',
    'latitude': '23.029544981',
    'area': '禅城区',
    'deviceName': '鸿运电脑城2号球机_1',
    'deviceBjTotal': 123,
    'proportion': '1.33%',
    'list': null,
    'title': null,
    'warnTypeCode': null,
    'deviceChanel': 'UN68QrpHA1BI9ESJ96R0MC'
  },
  {
    'bjTotal': null,
    'zlzgNum': null,
    'dxtxNum': null,
    'aiTodayBjNum': null,
    'aiJkTotal': null,
    'longitude': '113.115604113',
    'latitude': '23.045112691',
    'area': '禅城区',
    'deviceName': '燎原路2号球机',
    'deviceBjTotal': 112,
    'proportion': '1.21%',
    'list': null,
    'title': null,
    'warnTypeCode': null,
    'deviceChanel': 'UN68QrpHA1C8R84P1KH94U'
  },
  {
    'bjTotal': null,
    'zlzgNum': null,
    'dxtxNum': null,
    'aiTodayBjNum': null,
    'aiJkTotal': null,
    'longitude': '113.096613663',
    'latitude': '23.050588797',
    'area': '禅城区',
    'deviceName': '中山公园3号球机',
    'deviceBjTotal': 108,
    'proportion': '1.17%',
    'list': null,
    'title': null,
    'warnTypeCode': null,
    'deviceChanel': 'UN68QrpHA1C8R84P1OBC3T'
  },
  {
    'bjTotal': null,
    'zlzgNum': null,
    'dxtxNum': null,
    'aiTodayBjNum': null,
    'aiJkTotal': null,
    'longitude': '113.114430246',
    'latitude': '23.045558938',
    'area': '禅城区',
    'deviceName': '东方广场7号球机',
    'deviceBjTotal': 107,
    'proportion': '1.16%',
    'list': null,
    'title': null,
    'warnTypeCode': null,
    'deviceChanel': 'UN68QrpHA1C8R84P1P9T99'
  },
  {
    'bjTotal': null,
    'zlzgNum': null,
    'dxtxNum': null,
    'aiTodayBjNum': null,
    'aiJkTotal': null,
    'longitude': '113.103446018555',
    'latitude': '23.037768323113',
    'area': '禅城区',
    'deviceName': '中医院3号球机',
    'deviceBjTotal': 106,
    'proportion': '1.15%',
    'list': null,
    'title': null,
    'warnTypeCode': null,
    'deviceChanel': 'UN68QrpHA1C8R84P1OBC99'
  },
  {
    'bjTotal': null,
    'zlzgNum': null,
    'dxtxNum': null,
    'aiTodayBjNum': null,
    'aiJkTotal': null,
    'longitude': '113.104726334',
    'latitude': '23.043752789',
    'area': '禅城区',
    'deviceName': '鸿运电脑城3号球机',
    'deviceBjTotal': 102,
    'proportion': '1.10%',
    'list': null,
    'title': null,
    'warnTypeCode': null,
    'deviceChanel': 'UN68QrpHA1C8R84P1LFQ4L'
  },
  {
    'bjTotal': null,
    'zlzgNum': null,
    'dxtxNum': null,
    'aiTodayBjNum': null,
    'aiJkTotal': null,
    'longitude': '113.104969274',
    'latitude': '23.048039180',
    'area': '禅城区',
    'deviceName': '中医院3号球机',
    'deviceBjTotal': 102,
    'proportion': '1.10%',
    'list': null,
    'title': null,
    'warnTypeCode': null,
    'deviceChanel': 'UN68QrpHA1C8R84P1OBC99'
  },
  {
    'bjTotal': null,
    'zlzgNum': null,
    'dxtxNum': null,
    'aiTodayBjNum': null,
    'aiJkTotal': null,
    'longitude': '113.111568942',
    'latitude': '23.021212017',
    'area': '禅城区',
    'deviceName': '妇幼保健院2号球机',
    'deviceBjTotal': 101,
    'proportion': '1.09%',
    'list': null,
    'title': null,
    'warnTypeCode': null,
    'deviceChanel': 'UN68QrpHA1BI9ESJ94TQSH'
  },
  {
    'bjTotal': null,
    'zlzgNum': null,
    'dxtxNum': null,
    'aiTodayBjNum': null,
    'aiJkTotal': null,
    'longitude': '113.104983549',
    'latitude': '23.048012839',
    'area': '禅城区',
    'deviceName': '中山公园2号球机',
    'deviceBjTotal': 97,
    'proportion': '1.05%',
    'list': null,
    'title': null,
    'warnTypeCode': null,
    'deviceChanel': 'UN68QrpHA1C8R84P1OBC6B'
  },
  {
    'bjTotal': null,
    'zlzgNum': null,
    'dxtxNum': null,
    'aiTodayBjNum': null,
    'aiJkTotal': null,
    'longitude': '113.104869340222',
    'latitude': '23.045094964638',
    'area': '禅城区',
    'deviceName': '鸿运电脑城4号球机',
    'deviceBjTotal': 97,
    'proportion': '1.05%',
    'list': null,
    'title': null,
    'warnTypeCode': null,
    'deviceChanel': 'UN68QrpHA1BI9ESJ96R085'
  },
  {
    'bjTotal': null,
    'zlzgNum': null,
    'dxtxNum': null,
    'aiTodayBjNum': null,
    'aiJkTotal': null,
    'longitude': '113.114835907964',
    'latitude': '23.026751859554',
    'area': '禅城区',
    'deviceName': '市二医院2号球机',
    'deviceBjTotal': 97,
    'proportion': '1.05%',
    'list': null,
    'title': null,
    'warnTypeCode': null,
    'deviceChanel': 'UN68QrpHA1C8R84P1P9TKT'
  },
  {
    'bjTotal': null,
    'zlzgNum': null,
    'dxtxNum': null,
    'aiTodayBjNum': null,
    'aiJkTotal': null,
    'longitude': '113.100104244',
    'latitude': '23.050882481',
    'area': '禅城区',
    'deviceName': '佛平路-平桂路2号球机',
    'deviceBjTotal': 96,
    'proportion': '1.04%',
    'list': null,
    'title': null,
    'warnTypeCode': null,
    'deviceChanel': 'UN68QrpHA1C8R84P1Q8FEA'
  },
  {
    'bjTotal': null,
    'zlzgNum': null,
    'dxtxNum': null,
    'aiTodayBjNum': null,
    'aiJkTotal': null,
    'longitude': '113.104486664093',
    'latitude': '23.042969749617',
    'area': '禅城区',
    'deviceName': '鸿运电脑城1号球机',
    'deviceBjTotal': 94,
    'proportion': '1.02%',
    'list': null,
    'title': null,
    'warnTypeCode': null,
    'deviceChanel': 'UN68QrpHA1C8R84P1MEAOD'
  },
  {
    'bjTotal': null,
    'zlzgNum': null,
    'dxtxNum': null,
    'aiTodayBjNum': null,
    'aiJkTotal': null,
    'longitude': '113.124725579',
    'latitude': '23.038753839',
    'area': '禅城区',
    'deviceName': '南堤市场1号球机',
    'deviceBjTotal': 91,
    'proportion': '0.98%',
    'list': null,
    'title': null,
    'warnTypeCode': null,
    'deviceChanel': 'UN68QrpHA1C8R84P1LFPVK'
  },
  {
    'bjTotal': null,
    'zlzgNum': null,
    'dxtxNum': null,
    'aiTodayBjNum': null,
    'aiJkTotal': null,
    'longitude': '113.103453134',
    'latitude': '23.037814350',
    'area': '禅城区',
    'deviceName': '山紫市场1号球机',
    'deviceBjTotal': 90,
    'proportion': '0.97%',
    'list': null,
    'title': null,
    'warnTypeCode': null,
    'deviceChanel': 'UN68QrpHA1C8R84P1P9TI4'
  },
  {
    'bjTotal': null,
    'zlzgNum': null,
    'dxtxNum': null,
    'aiTodayBjNum': null,
    'aiJkTotal': null,
    'longitude': '113.103521137892',
    'latitude': '23.037807834206',
    'area': '禅城区',
    'deviceName': '中医院1号球机',
    'deviceBjTotal': 88,
    'proportion': '0.95%',
    'list': null,
    'title': null,
    'warnTypeCode': null,
    'deviceChanel': 'UN68QrpHA1C8R84P1R715Q'
  },
  {
    'bjTotal': null,
    'zlzgNum': null,
    'dxtxNum': null,
    'aiTodayBjNum': null,
    'aiJkTotal': null,
    'longitude': '113.115418664',
    'latitude': '23.035368586',
    'area': '禅城区',
    'deviceName': '同济市场1号球机',
    'deviceBjTotal': 87,
    'proportion': '0.94%',
    'list': null,
    'title': null,
    'warnTypeCode': null,
    'deviceChanel': 'UN68QrpHA1C8R84P1KH8NF'
  },
  {
    'bjTotal': null,
    'zlzgNum': null,
    'dxtxNum': null,
    'aiTodayBjNum': null,
    'aiJkTotal': null,
    'longitude': '113.106530399',
    'latitude': '23.029558547',
    'area': '禅城区',
    'deviceName': '中医院5号球机',
    'deviceBjTotal': 87,
    'proportion': '0.94%',
    'list': null,
    'title': null,
    'warnTypeCode': null,
    'deviceChanel': 'UN68QrpHA1BJDDJGTCLNQP'
  },
  {
    'bjTotal': null,
    'zlzgNum': null,
    'dxtxNum': null,
    'aiTodayBjNum': null,
    'aiJkTotal': null,
    'longitude': '113.111475871417',
    'latitude': '23.021132949135',
    'area': '禅城区',
    'deviceName': '同济市场5号球机',
    'deviceBjTotal': 82,
    'proportion': '0.89%',
    'list': null,
    'title': null,
    'warnTypeCode': null,
    'deviceChanel': 'UN68QrpHA1C8R84P1KH8QV'
  },
  {
    'bjTotal': null,
    'zlzgNum': null,
    'dxtxNum': null,
    'aiTodayBjNum': null,
    'aiJkTotal': null,
    'longitude': '113.099961279',
    'latitude': '23.049908773',
    'area': '禅城区',
    'deviceName': '中山公园1号球机',
    'deviceBjTotal': 81,
    'proportion': '0.88%',
    'list': null,
    'title': null,
    'warnTypeCode': null,
    'deviceChanel': 'UN68QrpHA1C8R84P1R70P3'
  },
  {
    'bjTotal': null,
    'zlzgNum': null,
    'dxtxNum': null,
    'aiTodayBjNum': null,
    'aiJkTotal': null,
    'longitude': '113.114717727',
    'latitude': '23.027867083',
    'area': '禅城区',
    'deviceName': '中医院1号球机',
    'deviceBjTotal': 76,
    'proportion': '0.82%',
    'list': null,
    'title': null,
    'warnTypeCode': null,
    'deviceChanel': 'UN68QrpHA1C8R84P1R715Q'
  },
  {
    'bjTotal': null,
    'zlzgNum': null,
    'dxtxNum': null,
    'aiTodayBjNum': null,
    'aiJkTotal': null,
    'longitude': '113.105757624658',
    'latitude': '23.029544981213',
    'area': '禅城区',
    'deviceName': '百花广场2号球机',
    'deviceBjTotal': 76,
    'proportion': '0.82%',
    'list': null,
    'title': null,
    'warnTypeCode': null,
    'deviceChanel': 'UN68QrpHA1BI9ESJ94TS0T'
  },
  {
    'bjTotal': null,
    'zlzgNum': null,
    'dxtxNum': null,
    'aiTodayBjNum': null,
    'aiJkTotal': null,
    'longitude': '113.116660388127',
    'latitude': '23.039356857539',
    'area': '禅城区',
    'deviceName': '东方广场6号球机',
    'deviceBjTotal': 72,
    'proportion': '0.78%',
    'list': null,
    'title': null,
    'warnTypeCode': null,
    'deviceChanel': 'UN68QrpHA1C8R84P1Q8F5Q'
  },
  {
    'bjTotal': null,
    'zlzgNum': null,
    'dxtxNum': null,
    'aiTodayBjNum': null,
    'aiJkTotal': null,
    'longitude': '113.103410205',
    'latitude': '23.037840680',
    'area': '禅城区',
    'deviceName': '市二医院2号球机',
    'deviceBjTotal': 66,
    'proportion': '0.71%',
    'list': null,
    'title': null,
    'warnTypeCode': null,
    'deviceChanel': 'UN68QrpHA1C8R84P1P9TKT'
  },
  {
    'bjTotal': null,
    'zlzgNum': null,
    'dxtxNum': null,
    'aiTodayBjNum': null,
    'aiJkTotal': null,
    'longitude': '113.103696273',
    'latitude': '23.040025126',
    'area': '禅城区',
    'deviceName': '东方广场8号球机',
    'deviceBjTotal': 64,
    'proportion': '0.69%',
    'list': null,
    'title': null,
    'warnTypeCode': null,
    'deviceChanel': 'UN68QrpHA1C8R84P1P9TCH'
  },
  {
    'bjTotal': null,
    'zlzgNum': null,
    'dxtxNum': null,
    'aiTodayBjNum': null,
    'aiJkTotal': null,
    'longitude': '113.103467481293',
    'latitude': '23.0377782021',
    'area': '禅城区',
    'deviceName': '中医院2号球机',
    'deviceBjTotal': 57,
    'proportion': '0.62%',
    'list': null,
    'title': null,
    'warnTypeCode': null,
    'deviceChanel': 'UN68QrpHA1C8R84P1Q8EN1'
  },
  {
    'bjTotal': null,
    'zlzgNum': null,
    'dxtxNum': null,
    'aiTodayBjNum': null,
    'aiJkTotal': null,
    'longitude': '113.112254372',
    'latitude': '23.044964987',
    'area': '禅城区',
    'deviceName': '中医院4号球机',
    'deviceBjTotal': 52,
    'proportion': '0.56%',
    'list': null,
    'title': null,
    'warnTypeCode': null,
    'deviceChanel': 'UN68QrpHA1C8R84P1P9SVV'
  },
  {
    'bjTotal': null,
    'zlzgNum': null,
    'dxtxNum': null,
    'aiTodayBjNum': null,
    'aiJkTotal': null,
    'longitude': '113.113872126',
    'latitude': '23.042354487',
    'area': '禅城区',
    'deviceName': '市二医院1号球机',
    'deviceBjTotal': 52,
    'proportion': '0.56%',
    'list': null,
    'title': null,
    'warnTypeCode': null,
    'deviceChanel': 'UN68QrpHA1C8R84P1R703J'
  },
  {
    'bjTotal': null,
    'zlzgNum': null,
    'dxtxNum': null,
    'aiTodayBjNum': null,
    'aiJkTotal': null,
    'longitude': '113.111955316',
    'latitude': '23.021712416',
    'area': '禅城区',
    'deviceName': '百花广场6号球机',
    'deviceBjTotal': 51,
    'proportion': '0.55%',
    'list': null,
    'title': null,
    'warnTypeCode': null,
    'deviceChanel': 'UN68QrpHA1BI9ESJ95SDBL'
  },
  {
    'bjTotal': null,
    'zlzgNum': null,
    'dxtxNum': null,
    'aiTodayBjNum': null,
    'aiJkTotal': null,
    'longitude': '113.115629211103',
    'latitude': '23.044990968534',
    'area': '禅城区',
    'deviceName': '南堤市场1号球机',
    'deviceBjTotal': 50,
    'proportion': '0.54%',
    'list': null,
    'title': null,
    'warnTypeCode': null,
    'deviceChanel': 'UN68QrpHA1C8R84P1LFPVK'
  },
  {
    'bjTotal': null,
    'zlzgNum': null,
    'dxtxNum': null,
    'aiTodayBjNum': null,
    'aiJkTotal': null,
    'longitude': '113.104754882',
    'latitude': '23.043739678',
    'area': '禅城区',
    'deviceName': '鸿运电脑城1号球机',
    'deviceBjTotal': 47,
    'proportion': '0.51%',
    'list': null,
    'title': null,
    'warnTypeCode': null,
    'deviceChanel': 'UN68QrpHA1C8R84P1MEAOD'
  },
  {
    'bjTotal': null,
    'zlzgNum': null,
    'dxtxNum': null,
    'aiTodayBjNum': null,
    'aiJkTotal': null,
    'longitude': '113.114921233425',
    'latitude': '23.035141106095',
    'area': '禅城区',
    'deviceName': '燎原路1号球机',
    'deviceBjTotal': 42,
    'proportion': '0.45%',
    'list': null,
    'title': null,
    'warnTypeCode': null,
    'deviceChanel': 'UN68QrpHA1C8R84P1Q8ETR'
  },
  {
    'bjTotal': null,
    'zlzgNum': null,
    'dxtxNum': null,
    'aiTodayBjNum': null,
    'aiJkTotal': null,
    'longitude': '113.105199609',
    'latitude': '23.028320829',
    'area': '禅城区',
    'deviceName': '东方广场1号球机',
    'deviceBjTotal': 41,
    'proportion': '0.44%',
    'list': null,
    'title': null,
    'warnTypeCode': null,
    'deviceChanel': 'UN68QrpHA1BJDDJGTDKAHF'
  },
  {
    'bjTotal': null,
    'zlzgNum': null,
    'dxtxNum': null,
    'aiTodayBjNum': null,
    'aiJkTotal': null,
    'longitude': '113.114802680',
    'latitude': '23.042250006',
    'area': '禅城区',
    'deviceName': 'IVSS_32',
    'deviceBjTotal': 40,
    'proportion': '0.43%',
    'list': null,
    'title': null,
    'warnTypeCode': null,
    'deviceChanel': 'UN68QrpHA1C8R84P1Q8F1E'
  },
  {
    'bjTotal': null,
    'zlzgNum': null,
    'dxtxNum': null,
    'aiTodayBjNum': null,
    'aiJkTotal': null,
    'longitude': '113.105328369',
    'latitude': '23.028781521',
    'area': '禅城区',
    'deviceName': '鸿运电脑城4号球机',
    'deviceBjTotal': 40,
    'proportion': '0.43%',
    'list': null,
    'title': null,
    'warnTypeCode': null,
    'deviceChanel': 'UN68QrpHA1BI9ESJ96R085'
  },
  {
    'bjTotal': null,
    'zlzgNum': null,
    'dxtxNum': null,
    'aiTodayBjNum': null,
    'aiJkTotal': null,
    'longitude': '113.124865275752',
    'latitude': '23.038309902806',
    'area': '禅城区',
    'deviceName': '佛平路-平桂街1号球机',
    'deviceBjTotal': 39,
    'proportion': '0.42%',
    'list': null,
    'title': null,
    'warnTypeCode': null,
    'deviceChanel': 'UN68QrpHA1C8R84P1Q8EGU'
  },
  {
    'bjTotal': null,
    'zlzgNum': null,
    'dxtxNum': null,
    'aiTodayBjNum': null,
    'aiJkTotal': null,
    'longitude': '113.09857463615',
    'latitude': '23.03432879043',
    'area': '禅城区',
    'deviceName': '妇幼保健院1号球机',
    'deviceBjTotal': 39,
    'proportion': '0.42%',
    'list': null,
    'title': null,
    'warnTypeCode': null,
    'deviceChanel': 'UN68QrpHA1BI9ESJ94TR2L'
  },
  {
    'bjTotal': null,
    'zlzgNum': null,
    'dxtxNum': null,
    'aiTodayBjNum': null,
    'aiJkTotal': null,
    'longitude': '113.103696274',
    'latitude': '23.040012000',
    'area': '禅城区',
    'deviceName': '东方广场2号球机',
    'deviceBjTotal': 36,
    'proportion': '0.39%',
    'list': null,
    'title': null,
    'warnTypeCode': null,
    'deviceChanel': 'UN68QrpHA1C8R84P1P9TFM'
  },
  {
    'bjTotal': null,
    'zlzgNum': null,
    'dxtxNum': null,
    'aiTodayBjNum': null,
    'aiJkTotal': null,
    'longitude': '113.116832478079',
    'latitude': '23.035133024852',
    'area': '禅城区',
    'deviceName': '燎原路2号球机',
    'deviceBjTotal': 34,
    'proportion': '0.37%',
    'list': null,
    'title': null,
    'warnTypeCode': null,
    'deviceChanel': 'UN68QrpHA1C8R84P1KH94U'
  },
  {
    'bjTotal': null,
    'zlzgNum': null,
    'dxtxNum': null,
    'aiTodayBjNum': null,
    'aiJkTotal': null,
    'longitude': '113.104869340',
    'latitude': '23.045094965',
    'area': '禅城区',
    'deviceName': '中山公园6号球机',
    'deviceBjTotal': 33,
    'proportion': '0.36%',
    'list': null,
    'title': null,
    'warnTypeCode': null,
    'deviceChanel': 'UN68QrpHA1C8R84P1LFQ0A'
  },
  {
    'bjTotal': null,
    'zlzgNum': null,
    'dxtxNum': null,
    'aiTodayBjNum': null,
    'aiJkTotal': null,
    'longitude': '113.099850367053',
    'latitude': '23.049905415414',
    'area': '禅城区',
    'deviceName': '火车站2号球机',
    'deviceBjTotal': 32,
    'proportion': '0.35%',
    'list': null,
    'title': null,
    'warnTypeCode': null,
    'deviceChanel': 'UN68QrpHA1C8R84P1MEATC'
  },
  {
    'bjTotal': null,
    'zlzgNum': null,
    'dxtxNum': null,
    'aiTodayBjNum': null,
    'aiJkTotal': null,
    'longitude': '113.104797856395',
    'latitude': '23.043611374532',
    'area': '禅城区',
    'deviceName': '鸿运电脑城3号球机',
    'deviceBjTotal': 31,
    'proportion': '0.34%',
    'list': null,
    'title': null,
    'warnTypeCode': null,
    'deviceChanel': 'UN68QrpHA1C8R84P1LFQ4L'
  },
  {
    'bjTotal': null,
    'zlzgNum': null,
    'dxtxNum': null,
    'aiTodayBjNum': null,
    'aiJkTotal': null,
    'longitude': null,
    'latitude': null,
    'area': null,
    'deviceName': null,
    'deviceBjTotal': 29,
    'proportion': '0.31%',
    'list': null,
    'title': null,
    'warnTypeCode': null,
    'deviceChanel': null
  },
  {
    'bjTotal': null,
    'zlzgNum': null,
    'dxtxNum': null,
    'aiTodayBjNum': null,
    'aiJkTotal': null,
    'longitude': '113.114946845',
    'latitude': '23.026916425',
    'area': '禅城区',
    'deviceName': '同济市场2号球机',
    'deviceBjTotal': 26,
    'proportion': '0.28%',
    'list': null,
    'title': null,
    'warnTypeCode': null,
    'deviceChanel': 'UN68QrpHA1C8R84P1R709V'
  },
  {
    'bjTotal': null,
    'zlzgNum': null,
    'dxtxNum': null,
    'aiTodayBjNum': null,
    'aiJkTotal': null,
    'longitude': '113.112225708099',
    'latitude': '23.04496496381',
    'area': '禅城区',
    'deviceName': '中山公园4号球机',
    'deviceBjTotal': 22,
    'proportion': '0.24%',
    'list': null,
    'title': null,
    'warnTypeCode': null,
    'deviceChanel': 'UN68QrpHA1BI9ESJ98O2TV'
  },
  {
    'bjTotal': null,
    'zlzgNum': null,
    'dxtxNum': null,
    'aiTodayBjNum': null,
    'aiJkTotal': null,
    'longitude': '113.106623473762',
    'latitude': '23.028236086765',
    'area': '禅城区',
    'deviceName': '百花广场5号球机',
    'deviceBjTotal': 21,
    'proportion': '0.23%',
    'list': null,
    'title': null,
    'warnTypeCode': null,
    'deviceChanel': 'UN68QrpHA1C8R84P1P9TPM'
  },
  {
    'bjTotal': null,
    'zlzgNum': null,
    'dxtxNum': null,
    'aiTodayBjNum': null,
    'aiJkTotal': null,
    'longitude': '113.105199609004',
    'latitude': '23.028320829127',
    'area': '禅城区',
    'deviceName': '百花广场6号球机',
    'deviceBjTotal': 20,
    'proportion': '0.22%',
    'list': null,
    'title': null,
    'warnTypeCode': null,
    'deviceChanel': 'UN68QrpHA1BI9ESJ95SDBL'
  },
  {
    'bjTotal': null,
    'zlzgNum': null,
    'dxtxNum': null,
    'aiTodayBjNum': null,
    'aiJkTotal': null,
    'longitude': '113.117050382811',
    'latitude': '23.041462607239',
    'area': '禅城区',
    'deviceName': '东方广场3号球机',
    'deviceBjTotal': 19,
    'proportion': '0.21%',
    'list': null,
    'title': null,
    'warnTypeCode': null,
    'deviceChanel': 'UN68QrpHA1BJDDJGTDK9DK'
  },
  {
    'bjTotal': null,
    'zlzgNum': null,
    'dxtxNum': null,
    'aiTodayBjNum': null,
    'aiJkTotal': null,
    'longitude': '113.113213795',
    'latitude': '23.040459106',
    'area': '禅城区',
    'deviceName': '燎原路1号球机',
    'deviceBjTotal': 18,
    'proportion': '0.19%',
    'list': null,
    'title': null,
    'warnTypeCode': null,
    'deviceChanel': 'UN68QrpHA1C8R84P1Q8ETR'
  },
  {
    'bjTotal': null,
    'zlzgNum': null,
    'dxtxNum': null,
    'aiTodayBjNum': null,
    'aiJkTotal': null,
    'longitude': '113.112087774125',
    'latitude': '23.02148876145',
    'area': '禅城区',
    'deviceName': '同济市场3号球机',
    'deviceBjTotal': 18,
    'proportion': '0.19%',
    'list': null,
    'title': null,
    'warnTypeCode': null,
    'deviceChanel': 'UN68QrpHA1C8R84P1R70ID'
  },
  {
    'bjTotal': null,
    'zlzgNum': null,
    'dxtxNum': null,
    'aiTodayBjNum': null,
    'aiJkTotal': null,
    'longitude': '113.103843844758',
    'latitude': '23.026734389769',
    'area': '禅城区',
    'deviceName': '山紫市场1号球机',
    'deviceBjTotal': 16,
    'proportion': '0.17%',
    'list': null,
    'title': null,
    'warnTypeCode': null,
    'deviceChanel': 'UN68QrpHA1C8R84P1P9TI4'
  },
  {
    'bjTotal': null,
    'zlzgNum': null,
    'dxtxNum': null,
    'aiTodayBjNum': null,
    'aiJkTotal': null,
    'longitude': '113.106279043854',
    'latitude': '23.042506881912',
    'area': '禅城区',
    'deviceName': '华强广场1号球机',
    'deviceBjTotal': 16,
    'proportion': '0.17%',
    'list': null,
    'title': null,
    'warnTypeCode': null,
    'deviceChanel': 'UN68QrpHA1C8R84P1KH933'
  },
  {
    'bjTotal': null,
    'zlzgNum': null,
    'dxtxNum': null,
    'aiTodayBjNum': null,
    'aiJkTotal': null,
    'longitude': '113.113193216344',
    'latitude': '23.026780042312',
    'area': '禅城区',
    'deviceName': '市二医院1号球机',
    'deviceBjTotal': 16,
    'proportion': '0.17%',
    'list': null,
    'title': null,
    'warnTypeCode': null,
    'deviceChanel': 'UN68QrpHA1C8R84P1R703J'
  },
  {
    'bjTotal': null,
    'zlzgNum': null,
    'dxtxNum': null,
    'aiTodayBjNum': null,
    'aiJkTotal': null,
    'longitude': '113.106418573225',
    'latitude': '23.042516831125',
    'area': '禅城区',
    'deviceName': '华强广场3号球机',
    'deviceBjTotal': 12,
    'proportion': '0.13%',
    'list': null,
    'title': null,
    'warnTypeCode': null,
    'deviceChanel': 'UN68QrpHA1C8R84P1Q8EOV'
  },
  {
    'bjTotal': null,
    'zlzgNum': null,
    'dxtxNum': null,
    'aiTodayBjNum': null,
    'aiJkTotal': null,
    'longitude': '113.116178110',
    'latitude': '23.025930569',
    'area': '禅城区',
    'deviceName': '中山公园5号球机',
    'deviceBjTotal': 12,
    'proportion': '0.13%',
    'list': null,
    'title': null,
    'warnTypeCode': null,
    'deviceChanel': 'UN68QrpHA1C8R84P1R70U5'
  },
  {
    'bjTotal': null,
    'zlzgNum': null,
    'dxtxNum': null,
    'aiTodayBjNum': null,
    'aiJkTotal': null,
    'longitude': '113.124704142018',
    'latitude': '23.038625514853',
    'area': '禅城区',
    'deviceName': '佛平路-平桂路2号球机',
    'deviceBjTotal': 12,
    'proportion': '0.13%',
    'list': null,
    'title': null,
    'warnTypeCode': null,
    'deviceChanel': 'UN68QrpHA1C8R84P1Q8FEA'
  },
  {
    'bjTotal': null,
    'zlzgNum': null,
    'dxtxNum': null,
    'aiTodayBjNum': null,
    'aiJkTotal': null,
    'longitude': '113.100420157709',
    'latitude': '23.034302984617',
    'area': '禅城区',
    'deviceName': '妇幼保健院3号球机',
    'deviceBjTotal': 11,
    'proportion': '0.12%',
    'list': null,
    'title': null,
    'warnTypeCode': null,
    'deviceChanel': 'UN68QrpHA1BI9ESJ93VA4V'
  },
  {
    'bjTotal': null,
    'zlzgNum': null,
    'dxtxNum': null,
    'aiTodayBjNum': null,
    'aiJkTotal': null,
    'longitude': '113.103810738316',
    'latitude': '23.040137061175',
    'area': '禅城区',
    'deviceName': '中医院4号球机',
    'deviceBjTotal': 11,
    'proportion': '0.12%',
    'list': null,
    'title': null,
    'warnTypeCode': null,
    'deviceChanel': 'UN68QrpHA1C8R84P1P9SVV'
  },
  {
    'bjTotal': null,
    'zlzgNum': null,
    'dxtxNum': null,
    'aiTodayBjNum': null,
    'aiJkTotal': null,
    'longitude': '113.112139854893',
    'latitude': '23.045007691667',
    'area': '禅城区',
    'deviceName': '中山公园3号球机',
    'deviceBjTotal': 10,
    'proportion': '0.11%',
    'list': null,
    'title': null,
    'warnTypeCode': null,
    'deviceChanel': 'UN68QrpHA1C8R84P1OBC3T'
  },
  {
    'bjTotal': null,
    'zlzgNum': null,
    'dxtxNum': null,
    'aiTodayBjNum': null,
    'aiJkTotal': null,
    'longitude': '113.099432996038',
    'latitude': '23.034355377493',
    'area': '禅城区',
    'deviceName': '妇幼保健院2号球机',
    'deviceBjTotal': 9,
    'proportion': '0.10%',
    'list': null,
    'title': null,
    'warnTypeCode': null,
    'deviceChanel': 'UN68QrpHA1BI9ESJ94TQSH'
  },
  {
    'bjTotal': null,
    'zlzgNum': null,
    'dxtxNum': null,
    'aiTodayBjNum': null,
    'aiJkTotal': null,
    'longitude': '113.106623473762',
    'latitude': '23.028236086765',
    'area': null,
    'deviceName': null,
    'deviceBjTotal': 9,
    'proportion': '0.10%',
    'list': null,
    'title': null,
    'warnTypeCode': null,
    'deviceChanel': null
  },
  {
    'bjTotal': null,
    'zlzgNum': null,
    'dxtxNum': null,
    'aiTodayBjNum': null,
    'aiJkTotal': null,
    'longitude': '113.106354175309',
    'latitude': '23.042506925128',
    'area': '禅城区',
    'deviceName': '华强广场2号球机',
    'deviceBjTotal': 9,
    'proportion': '0.10%',
    'list': null,
    'title': null,
    'warnTypeCode': null,
    'deviceChanel': 'UN68QrpHA1C8R84P1KH8V0'
  },
  {
    'bjTotal': null,
    'zlzgNum': null,
    'dxtxNum': null,
    'aiTodayBjNum': null,
    'aiJkTotal': null,
    'longitude': '113.116294786793',
    'latitude': '23.047063983365',
    'area': '禅城区',
    'deviceName': '南堤市场3号球机',
    'deviceBjTotal': 7,
    'proportion': '0.08%',
    'list': null,
    'title': null,
    'warnTypeCode': null,
    'deviceChanel': 'UN68QrpHA1C8HR7N69BT7B'
  },
  {
    'bjTotal': null,
    'zlzgNum': null,
    'dxtxNum': null,
    'aiTodayBjNum': null,
    'aiJkTotal': null,
    'longitude': '106.53995975',
    'latitude': '29.58210594',
    'area': '禅城区',
    'deviceName': '榴苑市场建设银行ATM机监控点',
    'deviceBjTotal': 6,
    'proportion': '0.06%',
    'list': null,
    'title': null,
    'warnTypeCode': null,
    'deviceChanel': '14'
  },
  {
    'bjTotal': null,
    'zlzgNum': null,
    'dxtxNum': null,
    'aiTodayBjNum': null,
    'aiJkTotal': null,
    'longitude': '113.096674499104',
    'latitude': '23.050486868575',
    'area': '禅城区',
    'deviceName': '火车站1号球机',
    'deviceBjTotal': 6,
    'proportion': '0.06%',
    'list': null,
    'title': null,
    'warnTypeCode': null,
    'deviceChanel': 'UN68QrpHA1C8R84P1Q8EK2'
  },
  {
    'bjTotal': null,
    'zlzgNum': null,
    'dxtxNum': null,
    'aiTodayBjNum': null,
    'aiJkTotal': null,
    'longitude': '113.115790308024',
    'latitude': '23.044954966469',
    'area': '禅城区',
    'deviceName': '南堤市场2号球机',
    'deviceBjTotal': 6,
    'proportion': '0.06%',
    'list': null,
    'title': null,
    'warnTypeCode': null,
    'deviceChanel': 'UN68QrpHA1BI9ESJ96QVB5'
  },
  {
    'bjTotal': null,
    'zlzgNum': null,
    'dxtxNum': null,
    'aiTodayBjNum': null,
    'aiJkTotal': null,
    'longitude': '113.116939519031',
    'latitude': '23.040087432135',
    'area': '禅城区',
    'deviceName': '东方广场5号球机',
    'deviceBjTotal': 5,
    'proportion': '0.05%',
    'list': null,
    'title': null,
    'warnTypeCode': null,
    'deviceChanel': 'UN68QrpHA1C8R84P1P9T2B'
  },
  {
    'bjTotal': null,
    'zlzgNum': null,
    'dxtxNum': null,
    'aiTodayBjNum': null,
    'aiJkTotal': null,
    'longitude': '113.120585',
    'latitude': '23.014256',
    'area': null,
    'deviceName': null,
    'deviceBjTotal': 5,
    'proportion': '0.05%',
    'list': null,
    'title': null,
    'warnTypeCode': null,
    'deviceChanel': null
  },
  {
    'bjTotal': null,
    'zlzgNum': null,
    'dxtxNum': null,
    'aiTodayBjNum': null,
    'aiJkTotal': null,
    'longitude': '113.114802680182',
    'latitude': '23.042250006419',
    'area': '禅城区',
    'deviceName': '东方广场1号球机',
    'deviceBjTotal': 5,
    'proportion': '0.05%',
    'list': null,
    'title': null,
    'warnTypeCode': null,
    'deviceChanel': 'UN68QrpHA1BJDDJGTDKAHF'
  },
  {
    'bjTotal': null,
    'zlzgNum': null,
    'dxtxNum': null,
    'aiTodayBjNum': null,
    'aiJkTotal': null,
    'longitude': '113.553055000',
    'latitude': '22.255564000',
    'area': '禅城区',
    'deviceName': '南风古灶公仔街监控点',
    'deviceBjTotal': 3,
    'proportion': '0.03%',
    'list': null,
    'title': null,
    'warnTypeCode': null,
    'deviceChanel': '3307179'
  },
  {
    'bjTotal': null,
    'zlzgNum': null,
    'dxtxNum': null,
    'aiTodayBjNum': null,
    'aiJkTotal': null,
    'longitude': 'ads',
    'latitude': 'ads',
    'area': '禅城区',
    'deviceName': '季华四路天桥（南）',
    'deviceBjTotal': 3,
    'proportion': '0.03%',
    'list': null,
    'title': null,
    'warnTypeCode': null,
    'deviceChanel': '330127170093056177'
  },
  {
    'bjTotal': null,
    'zlzgNum': null,
    'dxtxNum': null,
    'aiTodayBjNum': null,
    'aiJkTotal': null,
    'longitude': '113.104754882078',
    'latitude': '23.043739678496',
    'area': '禅城区',
    'deviceName': '鸿运电脑城2号球机_1',
    'deviceBjTotal': 3,
    'proportion': '0.03%',
    'list': null,
    'title': null,
    'warnTypeCode': null,
    'deviceChanel': 'UN68QrpHA1BI9ESJ96R0MC'
  },
  {
    'bjTotal': null,
    'zlzgNum': null,
    'dxtxNum': null,
    'aiTodayBjNum': null,
    'aiJkTotal': null,
    'longitude': '113.111572456233',
    'latitude': '23.02163640969',
    'area': '禅城区',
    'deviceName': '同济市场1号球机',
    'deviceBjTotal': 3,
    'proportion': '0.03%',
    'list': null,
    'title': null,
    'warnTypeCode': null,
    'deviceChanel': 'UN68QrpHA1C8R84P1KH8NF'
  },
  {
    'bjTotal': null,
    'zlzgNum': null,
    'dxtxNum': null,
    'aiTodayBjNum': null,
    'aiJkTotal': null,
    'longitude': '113.104898674511',
    'latitude': '23.034058227825',
    'area': '禅城区',
    'deviceName': '人民路交叉口1号球机_1',
    'deviceBjTotal': 3,
    'proportion': '0.03%',
    'list': null,
    'title': null,
    'warnTypeCode': null,
    'deviceChanel': 'UN68QrpHA1BI9ESJ96QV3Q'
  },
  {
    'bjTotal': null,
    'zlzgNum': null,
    'dxtxNum': null,
    'aiTodayBjNum': null,
    'aiJkTotal': null,
    'longitude': '113.106677105669',
    'latitude': '23.028739477554',
    'area': '禅城区',
    'deviceName': '百花广场3号球机',
    'deviceBjTotal': 3,
    'proportion': '0.03%',
    'list': null,
    'title': null,
    'warnTypeCode': null,
    'deviceChanel': 'UN68QrpHA1C8R84P1LFPSN'
  },
  {
    'bjTotal': null,
    'zlzgNum': null,
    'dxtxNum': null,
    'aiTodayBjNum': null,
    'aiJkTotal': null,
    'longitude': '113.10534622619',
    'latitude': '23.02869924918',
    'area': '禅城区',
    'deviceName': '百花广场1号球机',
    'deviceBjTotal': 2,
    'proportion': '0.02%',
    'list': null,
    'title': null,
    'warnTypeCode': null,
    'deviceChanel': 'UN68QrpHA1C8R84P1KH8SQ'
  },
  {
    'bjTotal': null,
    'zlzgNum': null,
    'dxtxNum': null,
    'aiTodayBjNum': null,
    'aiJkTotal': null,
    'longitude': '113.113771751825',
    'latitude': '23.04481167395',
    'area': '禅城区',
    'deviceName': '中山公园5号球机',
    'deviceBjTotal': 2,
    'proportion': '0.02%',
    'list': null,
    'title': null,
    'warnTypeCode': null,
    'deviceChanel': 'UN68QrpHA1C8R84P1R70U5'
  },
  {
    'bjTotal': null,
    'zlzgNum': null,
    'dxtxNum': null,
    'aiTodayBjNum': null,
    'aiJkTotal': null,
    'longitude': '113.112198695',
    'latitude': '23.021173033',
    'area': '禅城区',
    'deviceName': '居乐物业服务中心左监控点',
    'deviceBjTotal': 2,
    'proportion': '0.02%',
    'list': null,
    'title': null,
    'warnTypeCode': null,
    'deviceChanel': '13'
  },
  {
    'bjTotal': null,
    'zlzgNum': null,
    'dxtxNum': null,
    'aiTodayBjNum': null,
    'aiJkTotal': null,
    'longitude': '113.103453134',
    'latitude': '23.037814350',
    'area': '禅城区',
    'deviceName': '市府路1号球机',
    'deviceBjTotal': 2,
    'proportion': '0.02%',
    'list': null,
    'title': null,
    'warnTypeCode': null,
    'deviceChanel': 'UN68QrpHA1C8R84P1R71B1'
  },
  {
    'bjTotal': null,
    'zlzgNum': null,
    'dxtxNum': null,
    'aiTodayBjNum': null,
    'aiJkTotal': null,
    'longitude': 'ads',
    'latitude': 'ads',
    'area': '禅城区',
    'deviceName': '张槎文化广场监控点',
    'deviceBjTotal': 2,
    'proportion': '0.02%',
    'list': null,
    'title': null,
    'warnTypeCode': null,
    'deviceChanel': '330127170'
  },
  {
    'bjTotal': null,
    'zlzgNum': null,
    'dxtxNum': null,
    'aiTodayBjNum': null,
    'aiJkTotal': null,
    'longitude': null,
    'latitude': null,
    'area': '禅城区',
    'deviceName': '魁奇路地铁站B出口监控点',
    'deviceBjTotal': 2,
    'proportion': '0.02%',
    'list': null,
    'title': null,
    'warnTypeCode': null,
    'deviceChanel': '33012170'
  },
  {
    'bjTotal': null,
    'zlzgNum': null,
    'dxtxNum': null,
    'aiTodayBjNum': null,
    'aiJkTotal': null,
    'longitude': '113.105087341108',
    'latitude': '23.047884604485',
    'area': '禅城区',
    'deviceName': '中山公园2号球机',
    'deviceBjTotal': 1,
    'proportion': '0.01%',
    'list': null,
    'title': null,
    'warnTypeCode': null,
    'deviceChanel': 'UN68QrpHA1C8R84P1OBC6B'
  },
  {
    'bjTotal': null,
    'zlzgNum': null,
    'dxtxNum': null,
    'aiTodayBjNum': null,
    'aiJkTotal': null,
    'longitude': '113.099432996',
    'latitude': '23.034355377',
    'area': '禅城区',
    'deviceName': '季华四路天桥（南）',
    'deviceBjTotal': 1,
    'proportion': '0.01%',
    'list': null,
    'title': null,
    'warnTypeCode': null,
    'deviceChanel': '330127170093056177'
  },
  {
    'bjTotal': null,
    'zlzgNum': null,
    'dxtxNum': null,
    'aiTodayBjNum': null,
    'aiJkTotal': null,
    'longitude': '113.111955316',
    'latitude': '23.021712416',
    'area': '禅城区',
    'deviceName': '张槎文化广场监控点',
    'deviceBjTotal': 1,
    'proportion': '0.01%',
    'list': null,
    'title': null,
    'warnTypeCode': null,
    'deviceChanel': '330127170'
  },
  {
    'bjTotal': null,
    'zlzgNum': null,
    'dxtxNum': null,
    'aiTodayBjNum': null,
    'aiJkTotal': null,
    'longitude': '113.106530398556',
    'latitude': '23.029558547265',
    'area': '禅城区',
    'deviceName': '百花广场4号球机',
    'deviceBjTotal': 1,
    'proportion': '0.01%',
    'list': null,
    'title': null,
    'warnTypeCode': null,
    'deviceChanel': 'UN68QrpHA1BI9ESJ95SCVQ'
  },
  {
    'bjTotal': null,
    'zlzgNum': null,
    'dxtxNum': null,
    'aiTodayBjNum': null,
    'aiJkTotal': null,
    'longitude': '106.53995975',
    'latitude': '29.58210594',
    'area': '禅城区',
    'deviceName': '魁奇路地铁站B出口监控点',
    'deviceBjTotal': 1,
    'proportion': '0.01%',
    'list': null,
    'title': null,
    'warnTypeCode': null,
    'deviceChanel': '33012170'
  },
  {
    'bjTotal': null,
    'zlzgNum': null,
    'dxtxNum': null,
    'aiTodayBjNum': null,
    'aiJkTotal': null,
    'longitude': 'ads',
    'latitude': 'ads',
    'area': '禅城区',
    'deviceName': '江湾立交桥底2',
    'deviceBjTotal': 1,
    'proportion': '0.01%',
    'list': null,
    'title': null,
    'warnTypeCode': null,
    'deviceChanel': '330127170093056176'
  },
  {
    'bjTotal': null,
    'zlzgNum': null,
    'dxtxNum': null,
    'aiTodayBjNum': null,
    'aiJkTotal': null,
    'longitude': null,
    'latitude': null,
    'area': '禅城区',
    'deviceName': '江湾立交桥底2',
    'deviceBjTotal': 1,
    'proportion': '0.01%',
    'list': null,
    'title': null,
    'warnTypeCode': null,
    'deviceChanel': '330127170093056176'
  },
  {
    'bjTotal': null,
    'zlzgNum': null,
    'dxtxNum': null,
    'aiTodayBjNum': null,
    'aiJkTotal': null,
    'longitude': '113.131496',
    'latitude': '23.006757',
    'area': null,
    'deviceName': null,
    'deviceBjTotal': 1,
    'proportion': '0.01%',
    'list': null,
    'title': null,
    'warnTypeCode': null,
    'deviceChanel': null
  },
  {
    'bjTotal': null,
    'zlzgNum': null,
    'dxtxNum': null,
    'aiTodayBjNum': null,
    'aiJkTotal': null,
    'longitude': null,
    'latitude': null,
    'area': '禅城区',
    'deviceName': '榴苑市场建设银行ATM机监控点',
    'deviceBjTotal': 1,
    'proportion': '0.01%',
    'list': null,
    'title': null,
    'warnTypeCode': null,
    'deviceChanel': '14'
  },
  {
    'bjTotal': null,
    'zlzgNum': null,
    'dxtxNum': null,
    'aiTodayBjNum': null,
    'aiJkTotal': null,
    'longitude': '113.105108805417',
    'latitude': '23.047894484175',
    'area': '禅城区',
    'deviceName': '中山公园1号球机',
    'deviceBjTotal': 1,
    'proportion': '0.01%',
    'list': null,
    'title': null,
    'warnTypeCode': null,
    'deviceChanel': 'UN68QrpHA1C8R84P1R70P3'
  },
  {
    'bjTotal': null,
    'zlzgNum': null,
    'dxtxNum': null,
    'aiTodayBjNum': null,
    'aiJkTotal': null,
    'longitude': '113.13667',
    'latitude': '23.012079',
    'area': null,
    'deviceName': null,
    'deviceBjTotal': 1,
    'proportion': '0.01%',
    'list': null,
    'title': null,
    'warnTypeCode': null,
    'deviceChanel': null
  },
  {
    'bjTotal': null,
    'zlzgNum': null,
    'dxtxNum': null,
    'aiTodayBjNum': null,
    'aiJkTotal': null,
    'longitude': null,
    'latitude': null,
    'area': '禅城区',
    'deviceName': '居乐物业服务中心左监控点',
    'deviceBjTotal': 1,
    'proportion': '0.01%',
    'list': null,
    'title': null,
    'warnTypeCode': null,
    'deviceChanel': '13'
  },
  {
    'bjTotal': null,
    'zlzgNum': null,
    'dxtxNum': null,
    'aiTodayBjNum': null,
    'aiJkTotal': null,
    'longitude': '113.128046',
    'latitude': '23.01647',
    'area': null,
    'deviceName': null,
    'deviceBjTotal': 1,
    'proportion': '0.01%',
    'list': null,
    'title': null,
    'warnTypeCode': null,
    'deviceChanel': null
  },
  {
    'bjTotal': null,
    'zlzgNum': null,
    'dxtxNum': null,
    'aiTodayBjNum': null,
    'aiJkTotal': null,
    'longitude': '113.132214',
    'latitude': '23.013277',
    'area': null,
    'deviceName': null,
    'deviceBjTotal': 1,
    'proportion': '0.01%',
    'list': null,
    'title': null,
    'warnTypeCode': null,
    'deviceChanel': null
  },
  {
    'bjTotal': null,
    'zlzgNum': null,
    'dxtxNum': null,
    'aiTodayBjNum': null,
    'aiJkTotal': null,
    'longitude': '113.121578',
    'latitude': '23.000636',
    'area': null,
    'deviceName': null,
    'deviceBjTotal': 1,
    'proportion': '0.01%',
    'list': null,
    'title': null,
    'warnTypeCode': null,
    'deviceChanel': null
  },
  {
    'bjTotal': null,
    'zlzgNum': null,
    'dxtxNum': null,
    'aiTodayBjNum': null,
    'aiJkTotal': null,
    'longitude': '113.152988',
    'latitude': '23.048248',
    'area': null,
    'deviceName': null,
    'deviceBjTotal': 1,
    'proportion': '0.01%',
    'list': null,
    'title': null,
    'warnTypeCode': null,
    'deviceChanel': null
  },
  {
    'bjTotal': null,
    'zlzgNum': null,
    'dxtxNum': null,
    'aiTodayBjNum': null,
    'aiJkTotal': null,
    'longitude': '113.105328369',
    'latitude': '23.028781521',
    'area': '禅城区',
    'deviceName': '南风古灶1506监控点',
    'deviceBjTotal': 1,
    'proportion': '0.01%',
    'list': null,
    'title': null,
    'warnTypeCode': null,
    'deviceChanel': '3356170'
  },
  {
    'bjTotal': null,
    'zlzgNum': null,
    'dxtxNum': null,
    'aiTodayBjNum': null,
    'aiJkTotal': null,
    'longitude': '113.127184',
    'latitude': '23.001168',
    'area': null,
    'deviceName': null,
    'deviceBjTotal': 1,
    'proportion': '0.01%',
    'list': null,
    'title': null,
    'warnTypeCode': null,
    'deviceChanel': null
  },
  {
    'bjTotal': null,
    'zlzgNum': null,
    'dxtxNum': null,
    'aiTodayBjNum': null,
    'aiJkTotal': null,
    'longitude': '113.114835907964',
    'latitude': '23.026751859554',
    'area': '禅城区',
    'deviceName': '火车站2号球机',
    'deviceBjTotal': 1,
    'proportion': '0.01%',
    'list': null,
    'title': null,
    'warnTypeCode': null,
    'deviceChanel': 'UN68QrpHA1C8R84P1MEATC'
  },
  {
    'bjTotal': null,
    'zlzgNum': null,
    'dxtxNum': null,
    'aiTodayBjNum': null,
    'aiJkTotal': null,
    'longitude': '113.117003903494',
    'latitude': '23.040709237391',
    'area': '禅城区',
    'deviceName': '东方广场4号球机',
    'deviceBjTotal': 1,
    'proportion': '0.01%',
    'list': null,
    'title': null,
    'warnTypeCode': null,
    'deviceChanel': 'UN68QrpHA1C8R84P1P9T4P'
  },
  {
    'bjTotal': null,
    'zlzgNum': null,
    'dxtxNum': null,
    'aiTodayBjNum': null,
    'aiJkTotal': null,
    'longitude': '113.103696272885',
    'latitude': '23.040025126309',
    'area': '禅城区',
    'deviceName': '中医院5号球机',
    'deviceBjTotal': 1,
    'proportion': '0.01%',
    'list': null,
    'title': null,
    'warnTypeCode': null,
    'deviceChanel': 'UN68QrpHA1BJDDJGTCLNQP'
  }
];
